import type { SessionResult, Template } from "./types";

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: "tpl-gaoshu-basic",
    name: "高数 基础题",
    subject: "高等数学",
    chapter: "函数 极限 连续",
    problemType: "计算题",
    familiarity: 3,
    mastery: 3,
    thinkingMinutes: 2,
    solvingMinutes: 5,
    totalMinutes: 8,
    accent: "#0f8b8d",
  },
  {
    id: "tpl-gaoshu-hard",
    name: "高数 难题",
    subject: "高等数学",
    chapter: "综合题",
    problemType: "证明/压轴",
    familiarity: 2,
    mastery: 2,
    thinkingMinutes: 4,
    solvingMinutes: 10,
    totalMinutes: 15,
    accent: "#c7503c",
  },
  {
    id: "tpl-linear-choice",
    name: "线代 选择题",
    subject: "线性代数",
    chapter: "矩阵与向量",
    problemType: "选择题",
    familiarity: 4,
    mastery: 3,
    thinkingMinutes: 1,
    solvingMinutes: 3,
    totalMinutes: 4,
    accent: "#4a7c59",
  },
  {
    id: "tpl-probability",
    name: "概率论 中档题",
    subject: "概率论",
    chapter: "随机变量",
    problemType: "大题",
    familiarity: 3,
    mastery: 2,
    thinkingMinutes: 3,
    solvingMinutes: 7,
    totalMinutes: 12,
    accent: "#7a5c99",
  },
];

export const RESULT_LABELS: Record<SessionResult, string> = {
  solved: "做出",
  solved_overtime: "超时做出",
  stuck: "没思路",
  mistake: "算错",
  checked_answer: "看答案",
};
